
export const NATIONALITY_TO_CODE = {
    // A
    'Afghanistan': 'af',
    'South Africa': 'za',
    'Aland Islands': 'ax',
    'Albania': 'al',
    'Algeria': 'dz',
    'Germany': 'de',
    'Andorra': 'ad',
    'Angola': 'ao',
    'Anguilla': 'ai',
    'Antarctica': 'aq',
    'Antigua and Barbuda': 'ag',
    'Saudi Arabia': 'sa',
    'Argentina': 'ar',
    'Armenia': 'am',
    'Aruba': 'aw',
    'Australia': 'au',
    'Austria': 'at',
    'Azerbaijan': 'az',

    // B
    'Bahamas': 'bs',
    'Bahrain': 'bh',
    'Bangladesh': 'bd',
    'Barbados': 'bb',
    'Belarus': 'by',
    'Belgium': 'be',
    'Belize': 'bz',
    'Benin': 'bj',
    'Bermuda': 'bm',
    'Bhutan': 'bt',
    'Bolivia': 'bo',
    'Bonaire, Sint Eustatius and Saba': 'bq',
    'Bosnia and Herzegovina': 'ba',
    'Botswana': 'bw',
    'Bouvet Island': 'bv',
    'Brazil': 'br',
    'Brunei': 'bn',
    'Bulgaria': 'bg',
    'Burkina Faso': 'bf',
    'Burundi': 'bi',

    // C
    'Cabo Verde': 'cv',
    'Cayman Islands': 'ky',
    'Cambodia': 'kh',
    'Cameroon': 'cm',
    'Canada': 'ca',
    'Chile': 'cl',
    'China': 'cn',
    'Christmas Island': 'cx',
    'Cyprus': 'cy',
    'Cocos Islands': 'cc',
    'Colombia': 'co',
    'Comoros': 'km',
    'Congo': 'cg',
    'Democratic Republic of the Congo': 'cd',
    'Cook Islands': 'ck',
    'South Korea': 'kr',
    'North Korea': 'kp',
    'Costa Rica': 'cr',
    "Côte d'Ivoire": 'ci',
    'Croatia': 'hr',
    'Cuba': 'cu',
    'Curaçao': 'cw',

    // D
    'Denmark': 'dk',
    'Djibouti': 'dj',
    'Dominican Republic': 'do',
    'Dominica': 'dm',

    // E
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'United Arab Emirates': 'ae',
    'Ecuador': 'ec',
    'Eritrea': 'er',
    'Spain': 'es',
    'Estonia': 'ee',
    'United States': 'us',
    'Ethiopia': 'et',

    // F
    'Falkland Islands': 'fk',
    'Faroe Islands': 'fo',
    'Fiji': 'fj',
    'Finland': 'fi',
    'France': 'fr',

    // G
    'Gabon': 'ga',
    'Gambia': 'gm',
    'Georgia': 'ge',
    'South Georgia and the South Sandwich Islands': 'gs',
    'Ghana': 'gh',
    'Gibraltar': 'gi',
    'Greece': 'gr',
    'Grenada': 'gd',
    'Greenland': 'gl',
    'Guadeloupe': 'gp',
    'Guam': 'gu',
    'Guatemala': 'gt',
    'Guernsey': 'gg',
    'Guinea': 'gn',
    'Guinea-Bissau': 'gw',
    'Equatorial Guinea': 'gq',
    'Guyana': 'gy',
    'French Guiana': 'gf',

    // H
    'Haiti': 'ht',
    'Heard Island and McDonald Islands': 'hm',
    'Honduras': 'hn',
    'Hong Kong': 'hk',
    'Hungary': 'hu',

    // I
    'Isle of Man': 'im',
    'United States Minor Outlying Islands': 'um',
    'British Virgin Islands': 'vg',
    'United States Virgin Islands': 'vi',
    'India': 'in',
    'British Indian Ocean Territory': 'io',
    'Indonesia': 'id',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Ireland': 'ie',
    'Iceland': 'is',
    'Israel': 'il',
    'Italy': 'it',

    // J
    'Jamaica': 'jm',
    'Japan': 'jp',
    'Jersey': 'je',
    'Jordan': 'jo',

    // K
    'Kazakhstan': 'kz',
    'Kenya': 'ke',
    'Kyrgyzstan': 'kg',
    'Kiribati': 'ki',
    'Kuwait': 'kw',

    // L
    'Laos': 'la',
    'Lesotho': 'ls',
    'Latvia': 'lv',
    'Lebanon': 'lb',
    'Liberia': 'lr',
    'Libya': 'ly',
    'Liechtenstein': 'li',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',

    // M
    'Macau': 'mo',
    'North Macedonia': 'mk',
    'Madagascar': 'mg',
    'Malaysia': 'my',
    'Malawi': 'mw',
    'Maldives': 'mv',
    'Mali': 'ml',
    'Malta': 'mt',
    'Northern Mariana Islands': 'mp',
    'Morocco': 'ma',
    'Marshall Islands': 'mh',
    'Martinique': 'mq',
    'Mauritius': 'mu',
    'Mauritania': 'mr',
    'Mayotte': 'yt',
    'Mexico': 'mx',
    'Micronesia': 'fm',
    'Moldova': 'md',
    'Monaco': 'mc',
    'Mongolia': 'mn',
    'Montenegro': 'me',
    'Montserrat': 'ms',
    'Mozambique': 'mz',
    'Myanmar': 'mm',

    // N
    'Namibia': 'na',
    'Nauru': 'nr',
    'Nepal': 'np',
    'Nicaragua': 'ni',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'Niue': 'nu',
    'Norfolk Island': 'nf',
    'Norway': 'no',
    'New Caledonia': 'nc',
    'New Zealand': 'nz',

    // O
    'Oman': 'om',

    // P
    'Uganda': 'ug',
    'Uzbekistan': 'uz',
    'Pakistan': 'pk',
    'Palau': 'pw',
    'Palestine': 'ps',
    'Panama': 'pa',
    'Papua New Guinea': 'pg',
    'Paraguay': 'py',
    'Netherlands': 'nl',
    'Unknown Country': 'xx',
    'Multiple Countries': 'zz',
    'Peru': 'pe',
    'Philippines': 'ph',
    'Pitcairn': 'pn',
    'Poland': 'pl',
    'French Polynesia': 'pf',
    'Puerto Rico': 'pr',
    'Portugal': 'pt',

    // Q
    'Qatar': 'qa',

    // R
    'Syria': 'sy',
    'Central African Republic': 'cf',
    'Réunion': 're',
    'Romania': 'ro',
    'United Kingdom': 'gb',
    'England': 'gb-eng',
    'Russia': 'ru',
    'Rwanda': 'rw',

    // S
    'Western Sahara': 'eh',
    'Saint Barthélemy': 'bl',
    'Saint Kitts and Nevis': 'kn',
    'San Marino': 'sm',
    'Saint Martin (French part)': 'mf',
    'Sint Maarten (Dutch part)': 'sx',
    'Saint Pierre and Miquelon': 'pm',
    'Vatican City': 'va',
    'Saint Vincent and the Grenadines': 'vc',
    'Saint Helena, Ascension and Tristan da Cunha': 'sh',
    'Saint Lucia': 'lc',
    'Solomon Islands': 'sb',
    'Samoa': 'ws',
    'American Samoa': 'as',
    'Sao Tome and Principe': 'st',
    'Senegal': 'sn',
    'Serbia': 'rs',
    'Seychelles': 'sc',
    'Sierra Leone': 'sl',
    'Singapore': 'sg',
    'Slovakia': 'sk',
    'Slovenia': 'si',
    'Somalia': 'so',
    'Sudan': 'sd',
    'South Sudan': 'ss',
    'Sri Lanka': 'lk',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Suriname': 'sr',
    'Svalbard and Jan Mayen': 'sj',
    'Eswatini': 'sz',

    // T
    'Tajikistan': 'tj',
    'Taiwan': 'tw',
    'Tanzania': 'tz',
    'Chad': 'td',
    'Czech Republic': 'cz',
    'French Southern Territories': 'tf',
    'Thailand': 'th',
    'Timor-Leste': 'tl',
    'Togo': 'tg',
    'Tokelau': 'tk',
    'Tonga': 'to',
    'Trinidad and Tobago': 'tt',
    'Tunisia': 'tn',
    'Turkmenistan': 'tm',
    'Turks and Caicos Islands': 'tc',
    'Turkey': 'tr',
    'Tuvalu': 'tv',

    // U
    'Ukraine': 'ua',
    'Uruguay': 'uy',

    // V
    'Vanuatu': 'vu',
    'Venezuela': 've',
    'Vietnam': 'vn',

    // W
    'Wallis and Futuna': 'wf',

    // Y
    'Yemen': 'ye',

    // Z
    'Zambia': 'zm',
    'Zimbabwe': 'zw',

    // Obsolete codes (kept for authority records)
    'East Germany': 'dd',
    'Netherlands Antilles': 'an',
    'Czechoslovakia': 'cs',
    'USSR': 'su',
    'South Vietnam': 'vd',
    'Yugoslavia': 'yu',
    'Zaire': 'zr',
};

export const FLAG_API_BASE = 'https://flagcdn.com/24x18';
